#!/usr/bin/env ruby
#^syntax detection

site 'https://supermarket.getchef.com/api/v1'

# cookbook 'chef-client'

# cookbook 'apache2', '>= 1.0.0'

 cookbook 'rvm',
   :git => 'https://github.com/fnichol/chef-rvm'

# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'


#site 'http://community.opscode.com/api/v1'

# build-essential
# https://github.com/opscode-cookbooks/build-essential
cookbook 'build-essential', '2.0.0'

# apt
# https://github.com/opscode-cookbooks/apt
cookbook 'apt', '2.3.8'

# ark
# https://github.com/bryanwb/chef-ark
cookbook 'ark', '0.7.2'

# hostname
# https://github.com/3ofcoins/chef-cookbook-hostname
cookbook 'hostname', '0.1.0'

# nginx
# https://github.com/opscode-cookbooks/nginx
cookbook 'nginx', '2.7.4'

# ssh_known_hosts
# https://github.com/opscode-cookbooks/ssh_known_hosts
cookbook 'ssh_known_hosts', '1.3.0'

# user
# https://github.com/fnichol/chef-user
cookbook 'user', '0.3.0'

# apt-periodic
# https://github.com/madwork/chef-apt-periodic
cookbook 'apt-periodic', '0.1.1'

# chruby-build
# https://github.com/madwork/chef-chruby-build
cookbook 'chruby-build', '0.2.1'

# fail2ban
# https://github.com/opscode-cookbooks/fail2ban
cookbook 'fail2ban',
	:git => 'https://github.com/opscode-cookbooks/fail2ban'

# database
# https://github.com/opscode-cookbooks/database
cookbook 'database', '2.1.6'
